redis:
    image: redis
    
    container_name: cache
    
    expose:
      - 6379

app:
    build: ./
    
    volumes:
      - ./:/var/www/app
    
    links:
      - redis
    
    ports:
      - 3000:3000
    
    environment:
      - PORT=3000
      - NODE_ENV=development
      - REDIS_URL=redis://cache
    
    command:
      sh -c 'npm i && node server.js'

